services:

  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:deadbeef@postgres/postgres
    volumes:
      - ..:/workspace:cached

  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: deadbeef

volumes:
  postgres: