services:

  workspace:
    build: .
    command: nginx -g 'daemon off;'
    environment:
      DATABASE_URL: postgresql://postgres:deadbeef@postgres/postgres
    volumes:
      - ..:/workspace:cached
      - ./nginx.conf:/etc/nginx/sites-available/default
    working_dir: /workspace

  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: deadbeef

volumes:
  postgres: